swagger: "2.0"  
paths:  
  /validatePhoneNumber:  
    get:  
      description: "API для валидации телефонных номеров"  
      produces:  
      - "application/json"  
      parameters:  
      - name: "phone_number"  
        in: "query"  
        description: "Номер телефона"  
        required: true  
        type: "string"  
      responses:  
        "200":  
          description: "Successful operation"  
          schema:  
            oneOf:  
              - $$ref: "#/components/schemas/Success"  
              - $$ref: "#/components/schemas/Error"  
        "400":  
          description: "Invalid request"  
        "404":  
          description: "Not found"  
components:  
  schemas:  
    Success:  
      type: object  
      description: "Такой ответ возвращается, если передан валидный номер телефона"  
      properties:  
        status:  
          type: "boolean"  
          description: "Результат валидации"  
        normalized:  
          type: "string"  
          description: "Нормализованное значение вида +7-###-###-####, где # - цифра"  
          example: "+7-912-123-4567"  
    Error:  
      type: object  
      description: "Такой ответ возвращается, если передан невалидный номер телефона"  
      properties:  
        status:  
          type: "boolean"  
          description: "Результат валидации"
