name: CI

run-name: CI workflow

on:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache: true
          cache-dependency-path: go.sum

      - name: Display go version
        run: |
          go version
    
      - name: Install dependencies
        run: go mod verify
      
      - name: Build
        run: go build -o app cmd/phone-validator/main.go
      
      - name: Run tests
        run: |
          go test -v ./...