name: CI

run-name: CI workflow

on:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
        
      - name: Print Go version
        run: |
          go version